---
- name: Create k8s-binary-apiserver
  template: src=k8s-binary-apiserver.service.jinja2
            dest=/etc/systemd/system/k8s-binary-apiserver.service
  become: yes
  notify:
    - reload systemd
    - restart k8s-binary-apiserver

- name: Ensure k8s-binary-apiserver.service started
  service: name=k8s-binary-apiserver state=started enabled=yes args=--no-block
  become: yes