---
- name: Create k8s-binary-scheduler
  template: src=k8s-binary-kubelet.service.jinja2
            dest=/etc/systemd/system/k8s-binary-kubelet.service
  become: yes
  notify:
    - reload systemd
    - restart k8s-binary-kubelet

- name: Ensure k8s-binary-kubelet.service started
  service: name=k8s-binary-kubelet state=started enabled=yes args=--no-block
  become: yes