galaxy_info:
  author: Samsung CNCT
  description:
  company: Samsung CNCT
  license: Apache
  min_ansible_version: 1.2

dependencies:
  - {
      role: '{{ playbook_dir }}/roles/kraken.node/kraken.node.binary',
      when: "{{ kraken_config.node | selectattr('nodepool.kubeConfig.runMode', 'equalto', 'binary') | map(attribute='nodepool') | list | length }} > 0"
    }
  - {
      role: '{{ playbook_dir }}/roles/kraken.node/kraken.node.docker',
      when: "{{ kraken_config.node | selectattr('nodepool.kubeConfig.containerConfig.runtime', 'equalto', 'docker') | map(attribute='nodepool') | list | length }} > 0"
    }