---
- name: Run cluster {{kraken_action}}
  shell: >
    terraform apply -input=false {{playbook_dir}}/../terraform/ chdir={{playbook_dir}}/../terraform/
  when: kraken_action == 'up'

- name: Run terraform destroy
  shell: >
    terraform destroy -input=false -force {{playbook_dir}}/../terraform/ chdir={{playbook_dir}}/../terraform/
  when: kraken_action == 'down'
