---
- name: Make sure generated folder for cloud init snippets is there
  file: >
    path="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs"
    state=directory

- name: Generate RSA key
  command: openssl genrsa -out {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/cluster.key 2048

- name: Generate CSR
  command: >
    openssl req -new -sha256 
      -subj '/C={{kraken_aws_certs.certCountry | default('US')}}/ST={{kraken_aws_certs.certState | default('WA')}}/L={{kraken_aws_certs.certLocality | default('Seattle')}}/O={{kraken_aws_certs.certOrg | default('Kubernetes')}}/CN={{kraken_aws_certs.certCommonName | default(ssl_cert_common_name)}}'
      -key {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/cluster.key 
      -out {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/cluster.csr

- name: Generate self-signed SSL certificate
  command: >
    openssl req -nodes -x509 -days 365 
      -in {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/cluster.csr
      -key {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/cluster.key 
      -out {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/cluster.pem
      -extensions v3_ca