---
- name: Run cluster {{kraken_action}}
  shell: >
    terraform apply -input=false {{ config_base | expanduser }}/{{kraken_config.cluster}} chdir={{ config_base | expanduser }}/{{kraken_config.cluster}}
  when: kraken_action == 'up'

- name: Run terraform destroy
  shell: >
    terraform destroy -input=false -force {{ config_base | expanduser }}/{{kraken_config.cluster}} chdir={{ config_base | expanduser }}/{{kraken_config.cluster}}
  when: kraken_action == 'down'

- name: clean the terraform state generated prefix and other misc files.
  file:
    path: "{{ config_base | expanduser }}/{{kraken_config.cluster}}/{{item}}"
    state: absent
  when: kraken_action == 'down'
  with_items:
    - aws_prefix
    - terraform.tfstate
    - terraform.tfstate.backup