---
- name: Create k8s-binary-proxy
  template: src=k8s-binary-proxy.service.jinja2
            dest=/etc/systemd/system/k8s-binary-proxy.service
  become: yes
  notify:
    - reload systemd
    - restart k8s-binary-proxy

- name: Ensure k8s-binary-proxy.service started
  service: name=k8s-binary-proxy state=started enabled=yes args=--no-block
  become: yes