---
- name: Make sure generated folder for cloud init snippets is there
  file: >
    path="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs"
    state=directory

- name: Generate self-signed CA key
  command: >
    openssl genrsa -out {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/ca-key.pem 2048

- name: Generate self-signed CA
  command: >
    openssl req -x509 -new -nodes 
      -key {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/ca-key.pem 
      -days 7300 
      -out {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/ca.pem 
      -subj "/CN=kraken-ca"

- name: Generate etcd .write-files.cert-authority.part files
  template: src=write_files.cert-authority.part.jinja2
            dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/etcd.{{item.name}}.write-files.cert-authority.part"
  with_items: "{{kraken_config.etcd}}"

- name: Generate node .write-files.cert-authority.part files
  template: src=write_files.cert-authority.part.jinja2
            dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/node.{{item.name}}.write-files.cert-authority.part"
  with_items: "{{kraken_config.node}}"

- name: Generate master .write-files.cert-authority.part files
  template: src=write_files.cert-authority.part.jinja2
            dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/master.write-files.cert-authority.part"
  with_items: ["{{kraken_config.master}}"]