#cloud-config

---
write_files:
- path: /opt/bin/wait4etcdproxy.sh
  owner: root
  content: |
    #! /usr/bin/bash
    until curl http://127.0.0.1:4001/v2/machines; do sleep 2; done
- path: /opt/bin/flannelconfig.sh
  owner: root
  content: |
    #! /usr/bin/bash
    /usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'     
coreos:
  fleet:
    etcd-servers: http://$private_ipv4:4001
    public-ip: $private_ipv4
    metadata: "role=etcd-cluster"
  flannel:
    interface: $private_ipv4
    etcd-servers: http://__ETCD_IP__:4001
  units:
    - name: etcd.service
      command: start
      content: |
        Description=etcd 2.0 service
        Requires=early-docker.service
        After=early-docker.service
        Before=etcd-proxy.service

        [Service]
        EnvironmentFile=/etc/environment
        TimeoutStartSec=0
        SyslogIdentifier=writer_process
        ExecStartPre=-/usr/bin/docker kill etcd
        ExecStartPre=-/usr/bin/docker rm etcd
        ExecStartPre=/usr/bin/docker pull quay.io/coreos/etcd:v2.0.8
        ExecStart=/bin/bash -c "/usr/bin/docker run \
          -p 2379:2379 \
          -p 2380:2380 \
          --name etcd \
          -v /opt/etcd:/opt/etcd \
          -v /usr/share/ca-certificates/:/etc/ssl/certs \
          quay.io/coreos/etcd:v2.0.8 \
          -data-dir /opt/etcd \
          -name %H \
          -listen-client-urls http://0.0.0.0:2379 \
          -advertise-client-urls http://$COREOS_PRIVATE_IPV4:2379 \
          -listen-peer-urls http://0.0.0.0:2380 \
          -initial-advertise-peer-urls http://$COREOS_PRIVATE_IPV4:2380 \
          -initial-cluster master=http://__ETCD_IP__:2380 \
          -initial-cluster-state new"
        ExecStop=/usr/bin/docker kill etcd
        Restart=always
        RestartSec=10

        [X-Fleet]
        Conflicts=etcd*
    - name: etcd-proxy.service
      command: start
      content: |
        Description=etcd 2.0 proxy service
        Before=fleet.service
        After=etcd.service

        [Service]
        EnvironmentFile=/etc/environment
        TimeoutStartSec=0
        SyslogIdentifier=writer_process
        ExecStartPre=/usr/bin/docker pull quay.io/coreos/etcd:v2.0.8
        ExecStart=/bin/bash -c "/usr/bin/docker run \
          -p 4001:4001 \
          --name etcd-proxy \
          quay.io/coreos/etcd:v2.0.8 \
          -proxy on \
          -listen-client-urls http://0.0.0.0:4001 \
          -initial-cluster master=http://__ETCD_IP__:2380"
        ExecStop=/usr/bin/docker kill etcd-proxy
        Restart=always
        RestartSec=10
    - name: wait4etcdproxy.service
      command: start
      content: |
        [Unit]
        Description=etcd wait4etcdproxy
        Wants=network-online.target
        Wants=etcd.service
        After=etcd.service
        After=network-online.target
        Before=fleet.service

        [Service]
        ExecStartPre=/usr/bin/chmod +x /opt/bin/wait4etcdproxy.sh
        ExecStart=/usr/bin/bash /opt/bin/wait4etcdproxy.sh
        RemainAfterExit=true
        Type=oneshot
    - name: fleet.service
      command: start
    - name: flannelconfig.service
      command: start
      content: |
        [Unit]
        Description=write flannel network to etcd
        Wants=etcd-proxy.service
        After=etcd-proxy.service

        [Service]
        ExecStartPre=/usr/bin/chmod +x /opt/bin/flannelconfig.sh
        ExecStart=/usr/bin/bash /opt/bin/flannelconfig.sh
        RemainAfterExit=true
        Type=oneshot
  update:
    group: alpha
    reboot-strategy: __REBOOT_STRAT__