---
config_file: "{{ config_file | default('~/.kraken/config.yml' | expanduser) }}"
deployment:
  cluster: krakenCluster
  coreos:
    version: latest
    channel: stable
    rebootStrategy: off
  keypair:
    -
      name: krakenTesting
      publickeyFile: "{{ '~/.ssh/id_rsa.pub' | expanduser}}"
  kubeConfig:
    -
      name: allConfig
      version: 1.3.2
      runMode: container
      containerConfig: dockerconfig
  containerConfig:
    -
      name: dockerconfig
      version: 1.12.0
      runtime: docker
  fabric:
    provider: flannel
    options:
      backend: aws-vpc
  provider: aws
  providerConfig:
    resourcePrefix: defaults
    vpc: 10.0.0.0/16
    region: us-west-2
    subnet:
      -
        name: uwswest2a
        az: us-west-2a
        cidr: 10.0.1.0/22
      -
        name: uwswest2b
        az: us-west-2b
        cidr: 10.0.2.0/22
      -
        name: uwswest2c
        az: us-west-2c
        cidr: 10.0.3.0/22
    egressAcl:
      -
        protocol: "-1"
        rule_no: 100
        action: "allow"
        cidr_block: "0.0.0.0/0"
        from_port: 0
        to_port: 0
    ingressAcl:
      -
        protocol: "-1"
        rule_no: 100
        action: "allow"
        cidr_block: "0.0.0.0/0"
        from_port: 0
        to_port: 0
    authentication:
      accessKey:
      accessSecret:
      credentialsFile:
      credentialsProfile:
    ingressSecurity:
      - 
        from_port: 22
        to_port: 22
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      - 
        from_port: 8080
        to_port: 8080
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      - 
        from_port: 443
        to_port: 443
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      - 
        from_port: 8094
        to_port: 8094
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      - 
        from_port: 10250
        to_port: 10250
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      - 
        from_port: 10251
        to_port: 10251
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      - 
        from_port: 10252
        to_port: 10252
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      - 
        from_port: 10254
        to_port: 10254
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
      - 
        from_port: 30000
        to_port: 32767
        protocol: "TCP"
        cidr_blocks: ["0.0.0.0/0"]
    egressSecurity:
      - 
        from_port: 0
        to_port: 0
        protocol: "-1"
        cidr_blocks: ["0.0.0.0/0"]
  nodepool:
    -
      name: etcd
      count: 3
      providerConfig:
        type: m3.xlarge
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "One of three master instances"
        storage:
          -
            type: root
            volume: gp2
            size: 50
            delete: false
          -
            type: ebs
            deviceName: sdf
            volume: gp2
            size: 100
            delete: true
            snapshotId:
            encrypted: false
      keypair: krakenTesting
    -
      name: etcdEvents
      count: 3
      providerConfig:
        type: m3.xlarge
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "One of three master instances"
        storage:
          -
            type: root
            volume: gp2
            size: 50
            delete: false
          -
            type: ebs
            deviceName: sdf
            volume: gp2
            size: 100
            delete: true
            snapshotId:
            encrypted: false
      keypair: krakenTesting
    -
      name: masterNodes
      count: 3
      providerConfig:
        type: m3.xlarge
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "One of three master instances"
        storage:
          -
            type: root
            volume: gp2
            size: 50
            delete: false
          -
            type: ebs
            deviceName: sdf
            volume: gp2
            size: 100
            delete: true
            snapshotId:
            encrypted: false
      keypair: krakenTesting
      kubeConfig: allConfig
    -
      name: masterNodes
      count: 3
      providerConfig:
        type: m3.xlarge
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "One of three master instances"
        storage:
          -
            type: root
            volume: gp2
            size: 50
            delete: false
          -
            type: ebs
            deviceName: sdf
            volume: gp2
            size: 100
            delete: true
            snapshotId:
            encrypted: false
      keypair: krakenTesting
      kubeConfig: allConfig
    -
      name: apiServers
      count: 3
      providerConfig:
        type: m3.xlarge
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "One of three api server instances"
        storage:
          -
            type: root
            volume: gp2
            size: 50
            delete: false
          -
            type: ebs
            deviceName: sdf
            volume: gp2
            size: 100
            delete: true
            snapshotId:
            encrypted: false
      keypair: krakenTesting
      kubeConfig: allConfig
    -
      name: clusterNodes
      count: 90
      keypair: krakenTesting
      providerConfig:
        type: m3.medium
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "One of 90 nodes"
        storage:
          -
            type: root
            volume: gp2
            size: 50
            delete: false
          -
            type: ebs
            deviceName: sdf
            volume: gp2
            size: 100
            delete: true
            snapshotId:
            encrypted: false
      kubeConfig: allConfig
    -
      name: specialNodes
      count: 10
      keypair: krakenTesting
      providerConfig:
        type: m3.large
        subnet: ["uwswest2a", "uwswest2b", "uwswest2c"]
        tags:
          -
            key: comments
            value: "One of ten special nodes"
        storage:
          -
            type: root
            volume: gp2
            size: 50
            delete: false
          -
            type: ebs
            deviceName: sdf
            volume: gp2
            size: 100
            delete: true
            snapshotId:
            encrypted: false
      kubeConfig: allConfig
  etcd:
    -
      clientPorts: [2379, 4001]
      clusterToken: etcd-cluster-token
      name: etcd
      nodepool: etcd
      peerPorts: [2380]
      ssl: true
      version: 3.0.3
      containerConfig: dockerconfig
    -
      clientPorts: [2381]
      clusterToken: etcd-events-cluster-token
      name: etcdEvents
      nodepool: etcdEvents
      peerPorts: [2382]
      ssl: true
      version: 3.0.3
      containerConfig: dockerconfig
  master:
    nodepool: masterNodes
    loadbalancer: cloud
  node:
    - nodepool: clusterNodes
    - nodepool: specialNodes
  apiServer:
    nodepool: apiServers
    loadbalancer: cloud
  clusterServices:
    namespaces:
      - kube-system
    repos:
      -
        name: atlas
        url: http://atlas.cnct.io
    services:
      -
        name: kubedns
        repo: atlas
        chart: kubedns-0.1.0