- name: create kubeconfig entry
  command: > 
    kubectl config set-cluster {{ kraken_config.cluster }} 
      --server=https://{{kraken_endpoint}}
      --certificate-authority={{ config_base | expanduser }}/{{ kraken_config.cluster }}/certs/ca.pem
      --embed-certs=true
      --kubeconfig={{kubeconfig}}

- name: create user entry
  command: > 
    kubectl config set-credentials {{ kraken_config.cluster }}
      --username=admin
      --client-certificate={{ config_base | expanduser }}/{{ kraken_config.cluster }}/certs/end-user.crt
      --client-key={{ config_base | expanduser }}/{{ kraken_config.cluster }}/certs/end-user.key 
      --embed-certs=true
      --kubeconfig={{kubeconfig}}

- name: create context entry
  command: > 
    kubectl config set-context {{ kraken_config.cluster }}_context
      --cluster={{ kraken_config.cluster }}
      --user=admin
      --kubeconfig={{kubeconfig}}

- name: set current context
  command: > 
    kubectl config use-context {{ kraken_config.cluster }}_context
      --kubeconfig={{kubeconfig}}