---
- name: Make sure generated folder for generated key is there
  file: >
    path="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs"
    state=directory

- name: Generate self-signed CA key
  command: >
    openssl genrsa -out {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/service-account.pem 2048

- name: Generate master.write-files.service-account.part files
  template: src=write_files.cert-authority.part.jinja2
            dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/master.write-files.cert-authority.part"