---
- name: Make sure generated folder for generated key is there
  file: >
    path="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs"
    state=directory

- name: Generate self-signed CA key
  command: >
    openssl genrsa -out {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/service-account.pem 2048

- name: Extract public key
  command: >
    openssl rsa -in {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/service-account.pem 
      -outform PEM -pubout -out {{playbook_dir}}/../generated/{{kraken_config.cluster}}/certs/service-account-pub.pem

- name: Generate service-account-secret-manifest.yaml files
  template: src=service-account-secret-manifest.yaml.jinja2
            dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/service-account-secret-manifest.yaml"