---
kubeconfig: "{{ config_base | expanduser }}/{{kraken_config.cluster}}/admin.kubeconfig"
helm_home: "{{ config_base | expanduser }}/{{kraken_config.cluster}}/.helm"
tiller: tiller-deploy
tiller_image: 