---
- name: Check if configuration file exists
  stat: path={{ config_file | default(config_file_default) }}
  register: config_stat

- name: Include configuration variables from defaults file
  include_vars: "{{ role_path }}/files/config.yaml"

- name: Include configuration variables
  include_vars: "{{config_file}}"
  when: config_stat.stat.exists == True

- name: expand configuration and register the config fact
  set_fact:
    kraken_config: "{{ deployment | expand_config }}"

- name: set the kubernetes cloud provider fact
  set_fact:
    kraken_kubernetes_cloudprovider: "{{kraken_config.provider}}"
  when: "kraken_config.provider in ['aws', 'azure', 'cloudstack', 'gce', 'mesos', 'openstack', 'ovirt', 'rackspace', 'vsphere']"

- name: set the kubernetes cloud provider fact
  set_fact:
    kraken_kubernetes_cloudprovider: ""
  when: "kraken_config.provider not in ['aws', 'azure', 'cloudstack', 'gce', 'mesos', 'openstack', 'ovirt', 'rackspace', 'vsphere']"

- name: clean the generated folder
  file:
    path: "{{item}}"
    state: absent
  with_fileglob:
    - "{{playbook_dir}}/../generated/{{kraken_config.cluster}}/*.part"
    - "{{playbook_dir}}/../generated/{{kraken_config.cluster}}/*.manifest"
