---
- name: Check if configuration file exists
  stat: path={{ config_file | default(config_file_default) }}
  register: config_stat

- name: Include configuration variables from defaults file
  include_vars: "{{ role_path }}/files/config.yaml"

- name: Include configuration variables
  include_vars: "{{config_file}}"
  when: config_stat.stat.exists == True

- name: expand configuration and register the config fact
  set_fact:
    kraken_config: "{{ deployment | expand_config }}"
