---
- include: authenticate.yaml
- include: create-cluster.yaml
  when: kraken_action == 'up'
- include: create-nodepools.yaml
  when: kraken_action == 'up'
- include: destroy-cluster.yaml
  when: kraken_action == 'down'
- include: deauthenticate.yaml