---
- name: Create hyperkube-binary-apiserver
  template: src=hyperkube-binary-apiserver.service.ansible
            dest=/etc/systemd/system/hyperkube-binary-apiserver.service
  sudo: yes
  notify:
    - reload systemd
    - restart hyperkube-binary-apiserver