---
- name: Create /opt/bin/manifests for configs
  become: yes
  file: >
    path=/opt/bin/manifests
    state=directory
    owner=core
    group=core

- name: copy apiserver manifest config
  template: src=kubernetes-apiserver-pod.json.ansible
            dest=/opt/bin/manifests/apiserver.json
  become: yes

- name: Create hyperkube apiserver
  template: src=hyperkube-docker-apiserver.service.ansible
            dest=/etc/systemd/system/hyperkube-docker-apiserver.service
  become: yes
  notify:
    - reload systemd
    - restart hyperkube-docker-apiserver

- name: Ensure hyperkube-docker-apiserver.service started
  service: name=hyperkube-docker-apiserver state=started enabled=yes args=--no-block
  become: yes

