---
- name: set hostname
  command: hostnamectl set-hostname {{ inventory_hostname }}
  sudo: yes

- name: create logentries-url.service
  template: src=logentries-url.service.ansible dest=/etc/systemd/system/logentries-url.service
  sudo: yes
  when: logentries_token|default("") != ""
  notify:
    - reload systemd
    - restart logentries-url

- name: create logentries-token.service
  template: src=logentries-token.service.ansible dest=/etc/systemd/system/logentries-token.service
  sudo: yes
  when: logentries_token|default("") != ""
  notify:
    - reload systemd
    - restart logentries-token

- name: create install-kubectl.service
  template: src=install-kubectl.service.ansible dest=/etc/systemd/system/install-kubectl.service
  sudo: yes
  notify:
    - reload systemd
    - restart install-kubectl

- name: create install-hyperkube.service
  template: src=install-hyperkube.service.ansible dest=/etc/systemd/system/install-hyperkube.service
  sudo: yes
  notify:
    - reload systemd
    - restart install-hyperkube

- name: create journal-2-logentries.service
  template: src=journal-2-logentries.service.ansible dest=/etc/systemd/system/journal-2-logentries.service
  sudo: yes
  when: logentries_token|default("") != ""
  notify:
    - reload systemd
    - restart journal-2-logentries
