---

- name: Ensure dir for kubernetes credential files is created
  become: yes
  file: >
    path={{ kubernetes_cert_dir }}
    state=directory
    owner=core
    group=core

- name: Ensure CA configuration file is created
  become: yes
  template: >
    src=server-ca-config.json.ansible
    dest={{ kubernetes_cert_dir }}/server-ca-config.json

- name: Ensure CA CSR file is created
  become: yes
  template: >
    src=server-ca-csr.json.ansible
    dest={{ kubernetes_cert_dir }}/server-ca-csr.json

# Add certs to master
- name: Run generation script
  become: yes
  shell: >
    {{ kraken_local_dir }}/hack/generate_kube_cert.sh -e {{ etcd_private_ip }} -d {{ kubernetes_cert_dir }} -k kubernetes-auth
