---

- name: Create generate-kube-cert script
  template: src=generate-kube-cert.sh.ansible
            dest=/opt/bin/generate-kube-cert.sh

- name: Create generate-kube-cert service
  template: src=generate-kube-cert.ansible
            dest=/etc/systemd/system/generate-kube-cert.service
  sudo: yes
  notify:
    - reload systemd
    - reload generate-kube-cert.service