---

- name: Create kubernetes cert dir for kubernetes credential files
  become: yes
  file: >
    path={{ kubernetes_cert_dir }}
    state=directory
    owner=core
    group=core

- name: Generate for kube services users
  become: yes
  shell: >
    {{ kraken_local_dir }}/hack/generate_kube_auth.sh -e {{ etcd_private_ip }} -t -d {{ kubernetes_cert_dir }} -k kubernetes-auth -u "kubelet,kube_proxy,system:controller_manager,system:scheduler,system:logging,system:monitoring,system:dns"

- name: Generate for human user
  become: yes
  shell: >
    {{ kraken_local_dir }}/hack/generate_kube_auth.sh -e {{ etcd_private_ip }} -b -d {{ kubernetes_cert_dir }} -k kubernetes-auth -u "{{ cluster_user }}"
