---

- name: Create /opt/bin/kraken-services for custom binaries
  become: yes
  file: >
    path=/opt/bin/kraken-services
    state=directory
    owner=core
    group=core

- name: Download kraken-services
  git: repo={{kraken_services_repo}}
       dest=/opt/bin/kraken-services
       version={{kraken_services_branch}}
       accept_hostkey=yes
       force=yes
  become: yes
  notify:
    - reload systemd
    - restart kraken-render
    - restart kraken-create-services

- name: Create kraken-render script
  template: src=kraken-render.sh.ansible
            dest=/opt/bin/kraken-render.sh
  become: yes

- name: Create kraken-create-services script
  template: src=kraken-create-services.sh.ansible
            dest=/opt/bin/kraken-create-services.sh
  become: yes

- name: Create kraken-render
  template: src=kraken-render.service.ansible
            dest=/etc/systemd/system/kraken-render.service
  sudo: yes
  notify:
    - reload systemd
    - restart kraken-render

- name: Ensure kraken-render.service started
  service: name=kraken-render state=started enabled=yes args=--no-block
  become: yes

- name: Create kraken-create-services
  template: src=kraken-create-services.service.ansible
            dest=/etc/systemd/system/kraken-create-services.service
  become: yes
  notify:
    - reload systemd
    - restart kraken-create-services

- name: Ensure kraken-create-services.service started
  service: name=kraken-create-services state=started enabled=yes args=--no-block
  become: yes

