---
- name: Create kraken-create-services script
  template: src=kraken-create-services.sh.ansible
            dest=/opt/bin/kraken-create-services.sh
  become: yes

- name: Make kraken-create-services script executable
  become: yes
  file: path=/opt/bin/kraken-create-services.sh state=file mode="a+x"

- name: Create kraken-delete-services script
  template: src=kraken-delete-services.sh.ansible
            dest=/opt/bin/kraken-delete-services.sh
  become: yes

- name: Make kraken-delete-services script executable
  become: yes
  file: path=/opt/bin/kraken-delete-services.sh state=file mode="a+x"

- name: Create kraken kraken services
  become: yes
  shell: /opt/bin/kraken-create-services.sh 
  register: create_result 
  ignore_errors: yes

- name: Clean up kraken services
  become: yes
  shell: /opt/bin/kraken-delete-services.sh 
  ignore_errors: yes
  when: create_result.rc != 0

- fail: msg="Kraken services creation failed"
  when: create_result.rc != 0