---
- name: Create kraken-create-services script
  template: src=kraken-create-services.sh.ansible
            dest=/opt/bin/kraken-create-services.sh
  become: yes

- name: Create kraken-delete-services script
  template: src=kraken-delete-services.sh.ansible
            dest=/opt/bin/kraken-delete-services.sh
  become: yes

- name: Create kraken-create-services
  template: src=kraken-create-services.service.ansible
            dest=/etc/systemd/system/kraken-create-services.service
  become: yes
  notify:
    - reload systemd
    - restart kraken-create-services

- name: Ensure kraken-create-services.service started
  service: name=kraken-create-services state=started enabled=yes args=--no-block
  become: yes

