---

- name: Ensure kubernetes cert dir is created
  become: yes
  file: >
    path={{ kubernetes_cert_dir }}
    state=directory
    owner=core
    group=core

- name: Load for human user
  become: yes
  shell: >
    {{ kraken_local_dir }}/hack/load_kube_cert.sh -e {{ etcd_private_ip }} -k kubernetes-auth -d {{ kubernetes_cert_dir }}
