---
# Common tasks for every node
- include: common.yaml

- include: cadvisor.yaml
  when: "'master' in group_names or 'etcd' in group_names"

# Kubernetes master specific tasks
- include: master-binary.yaml
  when: "'master' in group_names and hyperkube_deployment_mode == 'binary'"
- include: master-docker.yaml
  when: "'master' in group_names and hyperkube_deployment_mode == 'docker'"
- include: kraken-services.yaml
  when: "'master' in group_names"

# Kubernetes node specific tasks
- include: node-binary.yaml
  when: "'node' in group_names and hyperkube_deployment_mode == 'binary'"
- include: node-docker.yaml
  when: "'node' in group_names and hyperkube_deployment_mode == 'docker'"
