---
# master-binary
- name: create install-hyperkube.service
  template: src=install-hyperkube.service.ansible dest=/etc/systemd/system/install-hyperkube.service
  sudo: yes
  notify:
    - reload systemd
    - restart install-hyperkube
    # XXX: since I haven't figured out how to get systemd to do this, nor figured out how to 
    #      parameterize a list of handlers for the install-hyperkube handler to notify
    - restart hyperkube-binary-controller-manager
    - restart hyperkube-binary-scheduler

- name: Ensure install-hyperkube.service started
  service: name=install-hyperkube state=started enabled=yes args=--no-block
  sudo: yes

- name: Create hyperkube-binary-controller-manager
  template: src=hyperkube-binary-controller-manager.service.ansible
            dest=/etc/systemd/system/hyperkube-binary-controller-manager.service
  sudo: yes
  notify:
    - reload systemd
    - restart hyperkube-binary-controller-manager

- name: Ensure hyperkube-binary-controller-manager.service started
  service: name=hyperkube-binary-controller-manager state=started enabled=yes args=--no-block
  sudo: yes

- name: Create hyperkube-binary-scheduler
  template: src=hyperkube-binary-scheduler.service.ansible
            dest=/etc/systemd/system/hyperkube-binary-scheduler.service
  sudo: yes
  notify:
    - reload systemd
    - restart hyperkube-binary-scheduler

- name: Ensure hyperkube-binary-scheduler.service started
  service: name=hyperkube-binary-scheduler state=started enabled=yes args=--no-block
  sudo: yes
