---

# master-binary

- name: Create hyperkube-binary-controller-manager
  template: src=hyperkube-binary-controller-manager.service.ansible
            dest=/etc/systemd/system/hyperkube-binary-controller-manager.service
  sudo: yes
  notify:
    - reload systemd
    - restart hyperkube-binary-controller-manager

- name: Create hyperkube-binary-scheduler
  template: src=hyperkube-binary-scheduler.service.ansible
            dest=/etc/systemd/system/hyperkube-binary-scheduler.service
  sudo: yes
  notify:
    - reload systemd
    - restart hyperkube-binary-scheduler