---

# master-docker

- name: Create /opt/bin/manifests for configs
  become: yes
  file: >
    path=/opt/bin/manifests
    state=directory
    owner=core
    group=core

- name: copy master manifest controller manager config
  template: src=kubernetes-master-pod-controller.json.ansible
            dest=/opt/bin/manifests/controller.json
  become: yes

- name: copy master manifest scheduler config
  template: src=kubernetes-master-pod-scheduler.json.ansible
            dest=/opt/bin/manifests/scheduler.json
  become: yes

- name: Create hyperkube-docker-master
  template: src=hyperkube-docker-master.service.ansible
            dest=/etc/systemd/system/hyperkube-docker-master.service
  become: yes
  notify:
    - reload systemd
    - restart hyperkube-docker-master

- name: Ensure hyperkube-docker-master.service started
  service: name=hyperkube-docker-master state=started enabled=yes args=--no-block
  become: yes

- name: Create hyperkube-docker-proxy
  template: src=hyperkube-docker-proxy.service.ansible
            dest=/etc/systemd/system/hyperkube-docker-proxy.service
  become: yes
  notify:
    - reload systemd
    - restart hyperkube-docker-proxy

- name: Ensure hyperkube-docker-proxy.service started
  service: name=hyperkube-docker-proxy state=started enabled=yes args=--no-block
  become: yes

