---

- name: Create kubernetes-label script
  template: src=kubernetes-label.sh.ansible
            dest=/opt/bin/kubernetes-label.sh
  become: yes
  notify:
    - reload systemd
    - restart kubernetes-label

- name: Create kubernetes-label
  template: src=kubernetes-label.service.ansible
            dest=/etc/systemd/system/kubernetes-label.service
  become: yes
  notify:
    - reload systemd
    - restart kubernetes-label

- name: Ensure kubernetes-label.service started
  service: name=kubernetes-label state=started enabled=yes args=--no-block
  become: yes

