---
- name: ensure custom facts directory exists
  file: >
    path=/etc/ansible/facts.d
    recurse=yes
    state=directory
  sudo: yes

- name: install custom fact module for IP address
  template: >
    src=node_ip_address_fact.sh.ansible
    dest=/etc/ansible/facts.d/kubernetes_node_ip_fact.fact
    mode=0755
  sudo: yes

- name: reload ansible_local
  setup: filter=ansible_local

- name: Wait for kubernetes master
  wait_for: host={{master_private_ip}} port=8080 timeout=300

- name: Create wait4node script
  template: src=wait4node.sh.ansible
            dest=/opt/bin/wait4node.sh
  sudo: yes

- name: Create wait4node service
  template: src=wait4node.service.ansible
            dest=/etc/systemd/system/wait4node.service
  sudo: yes

- name: Create hyperkube kubelet
  template: src=hyperkube-binary-kubelet.service.ansible
            dest=/etc/systemd/system/hyperkube-binary-kubelet.service
  sudo: yes

- name: Create hyperkube proxy
  template: src=hyperkube-binary-proxy.service.ansible
            dest=/etc/systemd/system/hyperkube-binary-proxy.service
  sudo: yes

- name: Create labeler service
  template: src=kubernetes-label.service.ansible
            dest=/etc/systemd/system/kubernetes-label.service
  sudo: yes

- name: notify systemd of config changes
  command: systemctl daemon-reload
  sudo: yes

- name: start hyperkube-binary-kubelet and set to start on startup
  service: name=hyperkube-binary-kubelet state=restarted enabled=yes
  sudo: yes

- name: start hyperkube-binary-proxy and set to start on startup
  service: name=hyperkube-binary-proxy state=restarted enabled=yes
  sudo: yes

- name: start wait4node and set to start on startup
  service: name=wait4node state=restarted enabled=yes
  sudo: yes

- name: start kubernetes-label and set to start on startup
  service: name=kubernetes-label state=restarted enabled=yes
  sudo: yes
