---

- name: Create hyperkube-docker-node
  template: src=hyperkube-docker-node.service.ansible
            dest=/etc/systemd/system/hyperkube-docker-node.service
  become: yes
  notify:
    - reload systemd
    - restart hyperkube-docker-node

- name: Ensure hyperkube-docker-node.service started
  service: name=hyperkube-docker-node state=started enabled=yes args=--no-block
  become: yes

- name: Create hyperkube-docker-node-proxy
  template: src=hyperkube-docker-proxy-node.service.ansible
            dest=/etc/systemd/system/hyperkube-docker-proxy-node.service
  become: yes
  notify:
    - reload systemd
    - restart hyperkube-docker-proxy-node

- name: Ensure hyperkube-docker-proxy-node.service started
  service: name=hyperkube-docker-proxy-node state=started enabled=yes args=--no-block
  become: yes
