galaxy_info:
  author: Samsung CNCT
  description:
  company: Samsung CNCT
  license: Apache
  min_ansible_version: 1.2

dependencies:
  - { role: '{{ playbook_dir }}/roles/kraken.fabric/kraken.fabric.flannel', when: kraken_config.fabric.provider == 'flannel' }
  - { role: '{{ playbook_dir }}/roles/kraken.fabric/kraken.fabric.calico', when: kraken_config.fabric.provider == 'calico' }