---
- name: set hostname
  command: hostnamectl set-hostname {{ inventory_hostname }}
  become: yes

- include: sysdig.yaml
- include: etcd.yaml
  when: not((logentries_token is undefined) or (logentries_token is none) or (logentries_token|trim == ''))
- include: logentries.yaml
  when: not((logentries_token is undefined) or (logentries_token is none) or (logentries_token|trim == ''))
