---
- name: Create sysdig-cloud-agent
  template: src=sysdig-cloud-agent.service.jinja2
            dest=/etc/systemd/system/sysdig-cloud-agent.service
  become: yes
  when: not((sysdigcloud_access_key is undefined) or (sysdigcloud_access_key is none) or (sysdigcloud_access_key|trim == ''))
  notify:
    - reload systemd
    - restart sysdig-cloud-agent

- name: Ensure sysdig-cloud-agent.service started
  service: name=sysdig-cloud-agent state=started enabled=yes args=--no-block
  when: not((sysdigcloud_access_key is undefined) or (sysdigcloud_access_key is none) or (sysdigcloud_access_key|trim == ''))
  become: yes