- name: Generate node kube proxy.yaml
  template: src=kube-proxy-manifest.yaml.jinja2
    dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/node.{{item.name}}.kube-proxy.yaml.manifest"
  with_items: "{{kraken_config.node}}"