---
- name: restart k8s-binary-scheduler
  service: name=k8s-binary-scheduler state=restarted enabled=yes
  become: yes
  when: (thirdparty_scheduler is undefined) or (thirdparty_scheduler is none) or (thirdparty_scheduler|trim == '')

- name: restart k8s-docker-scheduler
  service: name=k8s-docker-scheduler state=restarted enabled=yes
  become: yes
  when: (thirdparty_scheduler is undefined) or (thirdparty_scheduler is none) or (thirdparty_scheduler|trim == '')
