---
- name: Clean up kraken services, ignoring errors
  become: yes
  shell: >
    /opt/bin/kubectl --kubeconfig={{ controller_manager_settings.kubeconfig | expanduser }} delete -f /opt/bin/kraken-services/{{ item }}
  with_items: "{{ kraken_services_dirs.split(' ') }}"
  ignore_errors: yes

- name: Create kraken services, ignoring errors
  become: yes
  shell: >
    /opt/bin/kubectl --kubeconfig={{ controller_manager_settings.kubeconfig | expanduser }} create -f /opt/bin/kraken-services/{{ item }} || /opt/bin/kubectl --kubeconfig={{ controller_manager_settings.kubeconfig | expanduser }} apply -f /opt/bin/kraken-services/{{ item }}
  with_items: "{{ kraken_services_dirs.split(' ') }}"
