---
- name: Create /opt/bin/manifests for configs
  become: yes
  file: >
    path=/opt/bin/manifests
    state=directory
    owner=core
    group=core

- name: Copy controller manager manifest config
  template: src=k8s-controller-manager-pod-controller.json.jinja2
            dest=/opt/bin/manifests/controller-manager.json
  become: yes

- name: Create k8s-docker-controller-manager
  template: src=k8s-docker-controller-manager.service.jinja2
            dest=/etc/systemd/system/k8s-docker-controller-manager.service
  become: yes
  notify:
    - reload systemd
    - restart k8s-docker-controller-manager

- name: Ensure k8s-docker-controller-manager.service started
  service: name=k8s-docker-controller-manager state=started enabled=yes args=--no-block
  become: yes