---
- name: Create k8s-binary-controller-manager
  template: src=k8s-binary-controller-manager.service.jinja2
            dest=/etc/systemd/system/k8s-binary-controller-manager.service
  become: yes
  notify:
    - reload systemd
    - restart k8s-binary-controller-manager

- name: Ensure k8s-binary-controller-manager.service started
  service: name=k8s-binary-controller-manager state=started enabled=yes args=--no-block
  become: yes