---
- hosts: localhost
  roles:
    - { role: 'kraken.config', config_file: "{{ config_path | default('') }}" }
    - { role: 'roles/kraken.provider/kraken.provider.selector' }
    - { role: 'roles/kraken.clean' }