---
- hosts: localhost
  roles:
    - { role: 'kraken.config', config_file: "{{ config_path | default('') }}", tags: [ 'dryrun' ] }
    - { role: 'roles/kraken.provider/kraken.provider.selector' }
    - { role: 'roles/kraken.clean', tags: [ 'dryrun' ] }