- hosts: master
  gather_facts: False
  roles:
    - { role: ssh-wait, host: "{{ master_public_ip }}", delay: 5, timeout: 300 }
    - { role: ansible-coreos-bootstrap, coreos_pypy_url: 'https://bitbucket.org/squeaky/portable-pypy/downloads' }

- hosts: master
  roles:
    - kube-config