---
- hosts: etcd:master:nodes:apiservers
  gather_facts: False
  roles:
    - { role: sigma.coreos-bootstrap, coreos_pypy_version:2.6.1 }

- hosts: etcd:master:nodes:apiservers
  roles:
    - kubernetes

