---
- hosts: etcd:master:node:apiserver
  gather_facts: False
  roles:
    - { role: ansible-coreos-bootstrap, coreos_pypy_url: 'https://bitbucket.org/squeaky/portable-pypy/downloads' }

- hosts: etcd
  roles:
    - { role: kraken-etcd }

- hosts: master
  roles:
    - { role: kraken-master }

- hosts: node
  roles:
    - { role: kraken-node }

- hosts: apiserver
  roles:
    - { role: kraken-apiserver }