---
- hosts: cluster
  gather_facts: False
  roles:
    - { role: sigma.coreos-bootstrap, coreos_pypy_url: 'https://bitbucket.org/pypy/pypy/downloads' }

- hosts: cluster
  gather_facts: True
  roles:
    - kubernetes

- hosts: localhost
  sudo: false
  roles:
    - ssh-config
