---
- hosts: cluster
  gather_facts: False
  roles:
    - sigma.coreos-bootstrap

- hosts: cluster
  gather_facts: True
  roles:
    - kubernetes

- hosts: localhost
  sudo: false
  roles:
    - ssh-config
