#cloud-config

---
write_files:
  - path: /etc/ssl/ca-key.pem
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICHBTt1cAA2NhLWtleS5wZW0AbZW3suNYDERzfsXkqinRiwwmuPTe+0wUjei9/fp9s5suUiRdB43u379/huFF2fjluOCX5cgB8PhfKh//XfyGdFnmRyAzAKgssHlw5y7NP78mO2ey6BYsLaTicWG3YfATfWdUR0yYTytMTy8JqmI8FLs78fR0eh1CPz+pvAvrNgLbYdCzQOLOq+lRth1DC0n8Wvio0ziy+ciIdRVmGroxHlRrX6XckIrpnZfZcIFwnHZgs3MqqcDCTHiHl7ypvGbxNu1HWy6s22bqc1XhVFSnqgtp2QMr1lFSJS9cLR8R35ImyQicoQjToPtcPDl90hGdkuZLOHkZrmLkXuto0dD97WszlKuqyAnxfloo/fS6d9bh9Cua11fo3/2lyV/57J7UcjUWOcO0ayUGSzNzePcHIhdkT0CHKmQm6V4yOZahvd5GaKswX4pKy1Xnzi78E71DW+aADRgw/MDmt63b+80sxOoT2Rm04JKjPqdthdsSfzsMckl3flrTgFeEcvjyNdeBi8KOuBzbleeA2YJRx6JGKwEJ1MmDiIY51kaKaLbx3d1gd3cHqPtgaMFPa+8SIovTGHMSKsKTUP6wUt3dREYQ79c5+w0MoMHBMMLUitKoDUb0cAER0mm7v8FWj4phkB/y3nSt/wjGQuB07H8sUSk9ggHLaV4dV0J7047yZOmF5Tj5j036p9nqfBK/x68BZ7Mkc1xMqCzPgHgaacOQ+/2xtux55fRgMyMFxWziMzvtTML2eILe3ZMQ/fB7QXRqYOxCTkqVZ0+W7ZjvUcZBspOsPV7ak2rs98ssFGjjJSsFPFvGPHiswRrSq1aYh3ZNgSzla/ISFPxwpU+SCfNZOHXgkN5V2XMQSqeTXA5E4wqt6nPQceiLyTVDxDpzqU1/ehHuTfFuSsDP5d6LfEKDsPtxciFj1nfge1Upbp4EUKNbm8CIp67yax871swbapUQxO3SgmruCRxfcvhU1atnMi29Ym2xSRf+TzFcKW8IxVBi7uAVBQ5L1GNbIZrgJupHztsoo8R98QipQxDWfUiw/CH9B9W/KOPQ3wh94yYSQjP9EdVF8dqvKCSJHiWNdl1oMKZHxjDYbR+fPXN65fLjqD6qBsbnHFVIkGY9oskJLEGYjDYHp66Rycvvx8/dj/cbM7IpUO2fx/Q+nLxi6Lf5V/IPHmHfwQVkrS6iSaSOYoEcd23HAY+oq0dnhczOy2d5TyCt8hSMdcPcxWzH7xAd4OkJTfGJH27rS7lOkUdWZykGmQPo56Niimpwv6UbFNv1SKnn3hj2dw7b+BMLgbVbzdxJwyQ7aXknFztsuPSwN4VLCyjf117oEoz1KNsrxAUhpXLx/1IGscqkLayWNH7quMgE9l73b100iRV7YenR0ZLacBDpaaiKnOOmDwJl5vfQkpf66pWzanOJnU7ANZHjb1e/+ALX9HqY9vPwTEtyejsyNdQQ5vU6EtIq+cgGWn3Qm3S/Hf9RkdF375ft0TgSUrTYPEYLiFiG+ZrzZxRfKPI8lXZLDIjfjM23Vaa0OWwCTt6DwEH2wE7Lxcso+9wKBZ6F6cuUL8wu6ufVuCdJmdi706ksbhEIpcMR0P06bX0/1vBrWr4TLPOzUMRagDbPdOCURmkdWjfkAW80vVObNZmt1RjGGK4HCHX6L3HT4cdMfqL/UUn5JApdWubLoIjC9tGo6i2UhOxeqaBXaWkTO1mCP3+gf2uFN7j/r5t/AMIZbcePBgAA
  - path: /etc/ssl/ca.pem
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICHBTt1cAA2NhLnBlbQBlVEmvs0YQvPMrckdPBrMfcpiBAWMzmGGz4QY2uzcw+6+PX/J9UZTXt66uLpVUrf76+hREhmn/oSLXN3VTBT76Br8obJoqvaoqyI4FmEwICnMPHKflyQrz9c5jwBiq1xqemXIaQVCdAoAhmVENCCzskIIAY/XUL9Gpv6UVW0c+yPSJme0a8Nhv5qNGGKzB5IOt/2DkX+xbiPqt9FPo48ozJ41E+8MzNsvxYoOPA0iAVhTIAdpnTp4q9Wk+u1wzug7vFy3nweYxje5pfuNeXn33MF64fD8kPet4JN6kxrXqZwN1dM6sTpro1G33znev21MIJ+ut5cmcDSgT9krxSsJaOYXmfFbbNiGPlrhP/vbwlK4I+IX3IquPipihsvUFWPeCAz0A7XZeCk1Ze0uxdi+zESwkVczo7so07er6wD8HR+e3S1Nxec9JibuUDMV2Pmu793KZF/u6u/YktjuR20zrobZ9B4pyeXFV27zbFyliJVXptjdV5KqqLOaTJfsKNeaMcH/Eg5OxopSxNyzI1WJ6OB43Fn5pdKs4Qb31yUgS9i3ItrejX/RFLc/+0LyrY0tFemNd1rBRe2jCKib8O5066ChvtlHBhABIbIIRP+1IpIUuc4QwQrq5DDneCPmxOFFse20mdomTotE30wIxlA3ABldzIhGGCfgv+QcXTAb1TUYT0fHnvkAu/z9361fun6hbMZuZ5enMeXKPOx7ltKYFObVigZEmf0eLO7l9OVV0rEIGbZW4Cd1bbG8GG10eW36USD7o2b54rdZ2LuyHyDwV/YJTqtdO+IGAb1+NpeEtoIS0NV0nZUwmV0mDWTkOkco/FbN3a4Fz2eVscjroBt2TWpS2JiUew2AZDMQY/dHhUVQzaQ7T6LYXC9s/QDZ8PfXNJidiS+8rWo+B6Bmlp4+xtFFsWpeohKu1BqoRiR/XAQTnVrnfgLDkEtcr8HpjpE4Sz74X4UGwzsIUBodmkdkuiwR5YpI9pOT1qJRMzhXrozrX2+SU+FCnE/ZIG3FJX+pRhMuhXJCfuSyRX0Wn5d66msp+YnJpxn9Sf38FZGs/P8VfmGgAqUYEAAA=
coreos:
  units:
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            Requires=kraken-ssl.service
            After=kraken-ssl.service
            Environment="ETCD_SSL_DIR=/etc/etcd/ssl"
            ExecStartPre=/usr/bin/etcdctl -D etcd2379.etcd.testcluster.io \
              --cert-file /etc/etcd/ssl/client.pem --ca-file /etc/etcd/ssl/client-ca.pem --key-file /etc/etcd/ssl/client-key.pem \
              set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
      command: start
    - name: kraken-networking.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Setup Network Environment
        Requires=early-docker.service
        After=early-docker.service
        [Service]
        ExecStart=/usr/bin/docker run -v /etc:/etc --rm=true --net=host \
         quay.io/venezia/setup-network-environment:v1.0.1-mv
        RemainAfterExit=yes
        Type=oneshot
    - name: kraken-ssl.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Setup Network Environment
        Requires=early-docker.service
        Requires=kraken-networking.service
        After=early-docker.service
        After=kraken-networking.service
        [Service]
        EnvironmentFile=/etc/network-environment
        ExecStart=/usr/bin/docker run -v /etc/ssl:/input -v /etc:/output --rm=true \
         -e HOST_IP=${DEFAULT_IPV4} \
         quay.io/samsung_cnct/drunkensmee:v0.2 /assets/generate_apiserver.sh
        RemainAfterExit=yes
        Type=oneshot
    - name: format-ephemeral.service
      command: start
      content: |
        [Unit]
        Description=Formats the ephemeral drive
        After=dev-xvdf.device
        Requires=dev-xvdf.device
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/bash -c '(/usr/sbin/blkid -t TYPE=ext4 | /usr/bin/grep /dev/xvdf) || (/usr/sbin/wipefs -fa /dev/xvdf && /usr/sbin/mkfs.ext4 /dev/xvdf)'
    - name: ephemeral.mount
      command: start
      content: |
        [Unit]
        Description=Mount ephemeral to /ephemeral
        Requires=format-ephemeral.service
        After=format-ephemeral.service
        [Mount]
        What=/dev/xvdf
        Where=/ephemeral
        Type=ext4
  flannel:
    etcd_endpoints: https://etcd2379.etcd.testcluster.io:2379
    etcd_cafile: /etc/etcd/ssl/client-ca.pem
    etcd_certfile: /etc/etcd/ssl/client.pem
    etcd_keyfile: /etc/etcd/ssl/client-key.pem
  locksmith:
    endpoint: https://etcd2379.etcd.testcluster.io:2379
    etcd_cafile: /etc/etcd/ssl/client-ca.pem
    etcd_certfile: /etc/etcd/ssl/client.pem
    etcd_keyfile: /etc/etcd/ssl/client-key.pem
  update:
    group: stable
    reboot-strategy: etcd-lock