#cloud-config

---
write_files:
  - path: /etc/ssl/ca-key.pem
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICHBTt1cAA2NhLWtleS5wZW0AbZW3suNYDERzfsXkqinRiwwmuPTe+0wUjei9/fp9s5suUiRdB43u379/huFF2fjluOCX5cgB8PhfKh//XfyGdFnmRyAzAKgssHlw5y7NP78mO2ey6BYsLaTicWG3YfATfWdUR0yYTytMTy8JqmI8FLs78fR0eh1CPz+pvAvrNgLbYdCzQOLOq+lRth1DC0n8Wvio0ziy+ciIdRVmGroxHlRrX6XckIrpnZfZcIFwnHZgs3MqqcDCTHiHl7ypvGbxNu1HWy6s22bqc1XhVFSnqgtp2QMr1lFSJS9cLR8R35ImyQicoQjToPtcPDl90hGdkuZLOHkZrmLkXuto0dD97WszlKuqyAnxfloo/fS6d9bh9Cua11fo3/2lyV/57J7UcjUWOcO0ayUGSzNzePcHIhdkT0CHKmQm6V4yOZahvd5GaKswX4pKy1Xnzi78E71DW+aADRgw/MDmt63b+80sxOoT2Rm04JKjPqdthdsSfzsMckl3flrTgFeEcvjyNdeBi8KOuBzbleeA2YJRx6JGKwEJ1MmDiIY51kaKaLbx3d1gd3cHqPtgaMFPa+8SIovTGHMSKsKTUP6wUt3dREYQ79c5+w0MoMHBMMLUitKoDUb0cAER0mm7v8FWj4phkB/y3nSt/wjGQuB07H8sUSk9ggHLaV4dV0J7047yZOmF5Tj5j036p9nqfBK/x68BZ7Mkc1xMqCzPgHgaacOQ+/2xtux55fRgMyMFxWziMzvtTML2eILe3ZMQ/fB7QXRqYOxCTkqVZ0+W7ZjvUcZBspOsPV7ak2rs98ssFGjjJSsFPFvGPHiswRrSq1aYh3ZNgSzla/ISFPxwpU+SCfNZOHXgkN5V2XMQSqeTXA5E4wqt6nPQceiLyTVDxDpzqU1/ehHuTfFuSsDP5d6LfEKDsPtxciFj1nfge1Upbp4EUKNbm8CIp67yax871swbapUQxO3SgmruCRxfcvhU1atnMi29Ym2xSRf+TzFcKW8IxVBi7uAVBQ5L1GNbIZrgJupHztsoo8R98QipQxDWfUiw/CH9B9W/KOPQ3wh94yYSQjP9EdVF8dqvKCSJHiWNdl1oMKZHxjDYbR+fPXN65fLjqD6qBsbnHFVIkGY9oskJLEGYjDYHp66Rycvvx8/dj/cbM7IpUO2fx/Q+nLxi6Lf5V/IPHmHfwQVkrS6iSaSOYoEcd23HAY+oq0dnhczOy2d5TyCt8hSMdcPcxWzH7xAd4OkJTfGJH27rS7lOkUdWZykGmQPo56Niimpwv6UbFNv1SKnn3hj2dw7b+BMLgbVbzdxJwyQ7aXknFztsuPSwN4VLCyjf117oEoz1KNsrxAUhpXLx/1IGscqkLayWNH7quMgE9l73b100iRV7YenR0ZLacBDpaaiKnOOmDwJl5vfQkpf66pWzanOJnU7ANZHjb1e/+ALX9HqY9vPwTEtyejsyNdQQ5vU6EtIq+cgGWn3Qm3S/Hf9RkdF375ft0TgSUrTYPEYLiFiG+ZrzZxRfKPI8lXZLDIjfjM23Vaa0OWwCTt6DwEH2wE7Lxcso+9wKBZ6F6cuUL8wu6ufVuCdJmdi706ksbhEIpcMR0P06bX0/1vBrWr4TLPOzUMRagDbPdOCURmkdWjfkAW80vVObNZmt1RjGGK4HCHX6L3HT4cdMfqL/UUn5JApdWubLoIjC9tGo6i2UhOxeqaBXaWkTO1mCP3+gf2uFN7j/r5t/AMIZbcePBgAA
  - path: /etc/ssl/ca.pem
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICHBTt1cAA2NhLnBlbQBlVEmvs0YQvPMrckdPBrMfcpiBAWMzmGGz4QY2uzcw+6+PX/J9UZTXt66uLpVUrf76+hREhmn/oSLXN3VTBT76Br8obJoqvaoqyI4FmEwICnMPHKflyQrz9c5jwBiq1xqemXIaQVCdAoAhmVENCCzskIIAY/XUL9Gpv6UVW0c+yPSJme0a8Nhv5qNGGKzB5IOt/2DkX+xbiPqt9FPo48ozJ41E+8MzNsvxYoOPA0iAVhTIAdpnTp4q9Wk+u1wzug7vFy3nweYxje5pfuNeXn33MF64fD8kPet4JN6kxrXqZwN1dM6sTpro1G33znev21MIJ+ut5cmcDSgT9krxSsJaOYXmfFbbNiGPlrhP/vbwlK4I+IX3IquPipihsvUFWPeCAz0A7XZeCk1Ze0uxdi+zESwkVczo7so07er6wD8HR+e3S1Nxec9JibuUDMV2Pmu793KZF/u6u/YktjuR20zrobZ9B4pyeXFV27zbFyliJVXptjdV5KqqLOaTJfsKNeaMcH/Eg5OxopSxNyzI1WJ6OB43Fn5pdKs4Qb31yUgS9i3ItrejX/RFLc/+0LyrY0tFemNd1rBRe2jCKib8O5066ChvtlHBhABIbIIRP+1IpIUuc4QwQrq5DDneCPmxOFFse20mdomTotE30wIxlA3ABldzIhGGCfgv+QcXTAb1TUYT0fHnvkAu/z9361fun6hbMZuZ5enMeXKPOx7ltKYFObVigZEmf0eLO7l9OVV0rEIGbZW4Cd1bbG8GG10eW36USD7o2b54rdZ2LuyHyDwV/YJTqtdO+IGAb1+NpeEtoIS0NV0nZUwmV0mDWTkOkco/FbN3a4Fz2eVscjroBt2TWpS2JiUew2AZDMQY/dHhUVQzaQ7T6LYXC9s/QDZ8PfXNJidiS+8rWo+B6Bmlp4+xtFFsWpeohKu1BqoRiR/XAQTnVrnfgLDkEtcr8HpjpE4Sz74X4UGwzsIUBodmkdkuiwR5YpI9pOT1qJRMzhXrozrX2+SU+FCnE/ZIG3FJX+pRhMuhXJCfuSyRX0Wn5d66msp+YnJpxn9Sf38FZGs/P8VfmGgAqUYEAAA=
  - path: /etc/kubernetes/manifests/apiserver.yaml
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICJJiwFcAA2FwaXNlcnZlci55YW1sAJ1UTW/bMAy951foB0R2snRbZ8CHYdut67oO2LVQZcYRIluGRDv1v58of9VNHGxDLhHJ9yi+J1pU6jdYp0yZsGa7OqoyS9iDyVYFoMgEimTFWCkKSNixfgYuKuXANmD7sKuEHHKudQjFylUgCXUwDu8BT8YeE4a2Bh+TpkShSt+RKvgSM2OqELnP5NJGysS5MbmGpwkdH9oKLOGSZhvtovcBJE1RCD9AOHA2FfWBeQvOOH/283KRZRacSzdR+I1JQJnxDuDSA2Llkjim4Lvdx08R/YkQHEpd+7npngkl5nAp9kpDSrAAjZ3TsdQKSvS5qPJ6zevB4iLivPwI7TK/T84QQmtz4pVVjYfkkKW9KV2WBlUSeD8OVxW3oswh3W6iLekSbz+8Kpa1hafKWExvbnZTi6xQjl4TJ6+s0en98Eju1B5kKzWsx9C3F+XQre9UofCRetn1LyJW2H7xcHjBr1C2PhZu9llKU5e4fgRnaivhZ21QjJ1RuyAen/Qg520J3qOgyuj+TBTCkSQCgQT7C/iZrqOdy+A3Vg9ai26k/29s6szf3jQqA5uKkxtT2uTo98+H7WQz2eWG7RiX6cFHEza42O3t21i3p2EHLsNvN7ebM/yrYEegjRQ6RBqj6wK+0/TjjQo6PQg8JOyCDjMifw5uOz4V9QUWRPaj1O34zblEPazKAiml/4UuWEzIBT6SZImvU6L/HgbtiLevrq6qcVWLq2Sz+RemXySonY3dQVjwzzpA1F5JMThwafY/fZ9OZGYGAAA=
  - path: /etc/kubernetes/kubeconfig.yaml
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICEIrv1cAA2t1YmUtY29uZmlnLnlhbWwAdY/BDsIgEETvfAU/gMQrV//BO+JWN6XQLEujfy8gNq3R225m5mXGzngGShiDkctRjBiuRp5iGPAmnM+Ji2iEksFOYKSPznohZVdMOcsDxDigswzKZr5HQn4aqYGdHvMFKABD0il57exhhknktKNWkwcusCp0qEcIrDbs30Q7Y8ksQA28SY7wp8OaqJaWcjEwPLg16venxHvmurs33DTeLVA9LVwmavU77dvwArkGlfh2AQAA
  - path: /etc/kubernetes/manifests/kube-proxy.yaml
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICI5kwFcAA2t1YmUtcHJveHkueWFtbABtULtuwzAM3P0V/AFZcYuigYBMndtm6lowMmsLsR6QaDf++8q24iyFJh15Dx4G80UxGe8UTE11Na5VcPZtZYmxRUZVATi0pOA6XkiE6G9zgVJAfcfTnJhslQLphdH7xB/Evz5eFXAcKWPaO0bjstuyIf5TBTAWu4x2OtbGy877bqDvB1P2c6C4cNTU1M/1y0rS3lrMwdePgMdSAR7yAoSwmKPGU88clJTN02t9yK9Rx8PxsC+tFGF9SycTGC8DpX02+I7zfS3FeCq3ASTSYzQ8v+WsdOMtC2RrM5mBOmr3HgAmP4yW3v3oON1D2+V3Ru4VSGItUxqkpsipCG1tZVSsqFgaLqNI2H66Yd4dNv1S87K46t4TbR5jijL1GElqXCXNj9HI5cz/3P4ANr/RACsCAAA=
  - path: /etc/kubernetes/manifests/kube-scheduler.yaml
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICHBmwFcAA2t1YmUtc2NoZWR1bGVyLnlhbWwAdVDJasQwDL3nK/QDzjIldDDMrTC3MlDotaiOSMx4w1ZS0q+vk2YSeig66S3SkzDod4pJeydhaoq7dp2Em+8KS4wdMsoCwKElCffxk0RSA3WjobjBKaDauTkx2SIFUotr8Ilfib98vEvgOFLGlHeM2uWNi0L8NxlAW+wz06tYal/13veGPg53NcyB4uKTU1M+le1qUt5azAesjYBDtAF/VwgQwmKOHC8Dc5BV1ZyeyzpXI8/1ud5FhrCjKMiQ4st2CIDREzlK6RZ9TrFC+eY86Er8aH+fIGEfvOMBeZA5IaHh4fuAfVzk9al9SLXTrNG8kMH5jfIHupQF7caytuRHPogfJ+VQLtABAAA=
  - path: /etc/kubernetes/manifests/kube-controller-manager.yaml
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICGVmwFcAA2t1YmUtY29udHJvbGxlci1tYW5hZ2VyLnlhbWwAjVLLbtswELzrK/gDlGwHRgICvhXoqa2BAL0GW2pjEeZDWK5UKF8fUk8UjdJCF+3szCx3SGjNT6RogleiPxZ342slrqEuHDLUwKAKITw4VOLe/UKpg2cK1iJJBx5uSHM/tqAXUhwioytiizrLmxD5O/LvQHclmDpMWPYB49PozJD/HCGEcelXiZum0oTqFsLN4stmUzVDi5QNVH8sH8rzKNLBJY9ajYUUG2kGdmZJIVOdlqBLw9yqqjqeHstD+o7q6fB0WEkWoU5atKj5Mq82dSJSbzRK0Dp0nmVLpgdGecdBvhqLlwpZVzHaSkMGyzYltogpBJYJ34j5zOSRMc6alW9Njx5jvFJIu49Qijyd+ivyUk53oMS6xYq3wI1KuSBYbt42OFCmH07n04wZb9iA/YIWhmdMudUxEc5zl43D0PHWGPE+2M7ht7x/XK7A5eo6Tf17sdlueg2plhqJo9xIM4FS7j+8Hdb39JH1vt/W+V+jahTu2OVw9/ymDOZXnomjb/FH+js5fJrCp2Z7DhO+K+0iVbEBwvwms8K8Gg1L6h9t/Q4hZumLPwQAAA==
  - path: /etc/kubernetes/manifests/kube-system-namespace.yaml
    owner: root
    permissions: 0644
    encoding: "gz+b64"
    content: |
      H4sICCzCwFcAA2t1YmUtc3lzdGVtLW5hbWVzcGFjZS55YW1sAMvOzEuxUvBLzE0tLkhMTuVKLMgMSy0qzszPs1IoM+TKTS1JTEksSbTiUlDIAyqyUsguTUrVLa4sLknNBYrlJCal5hSDZLHIAwCSQLiQXAAAAA==
coreos:
  units:
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            Requires=kraken-ssl.service
            After=kraken-ssl.service
            Environment="ETCD_SSL_DIR=/etc/etcd/ssl"
            ExecStartPre=/usr/bin/etcdctl -D etcd2379.etcd.testcluster.io \
              --cert-file /etc/etcd/ssl/client.pem --ca-file /etc/etcd/ssl/client-ca.pem --key-file /etc/etcd/ssl/client-key.pem \
              set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
            ExecStartPre=-/usr/bin/mkdir -p /opt/cni
            ExecStartPre=/usr/bin/wget -N -P /opt/cni https://storage.googleapis.com/kubernetes-release/network-plugins/cni-8a936732094c0941e1543ef5d292a1f4fffa1ac5.tar.gz
            ExecStartPre=/usr/bin/tar -xzf /opt/cni/cni-8a936732094c0941e1543ef5d292a1f4fffa1ac5.tar.gz -C /opt/cni/
            ExecStartPre=/usr/bin/rm /opt/cni/cni-8a936732094c0941e1543ef5d292a1f4fffa1ac5.tar.gz
      command: start
    - name: kraken-networking.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Setup Network Environment
        Requires=network-online.target
        After=network-online.target
        [Service]
        RemainAfterExit=yes
        Type=oneshot
        ExecStart=/usr/bin/rkt run \
         --insecure-options=image \
         --net=host \
         --inherit-env=true \
         --volume etc,kind=host,source=/etc,readOnly=false \
         --mount volume=etc,target=/etc \
         quay.io/samsung_cnct/setup-network-environment:v1.0.1-mv
        ExecStopPost=/usr/bin/rkt gc --mark-only
    - name: kraken-ssl.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Setup Network Environment
        Requires=kraken-networking.service
        After=kraken-networking.service
        [Service]
        EnvironmentFile=/etc/network-environment
        RemainAfterExit=yes
        Type=oneshot
        ExecStart=/usr/bin/rkt run \
         --insecure-options=image \
         --inherit-env=true \
         --volume input,kind=host,source=/etc/ssl,readOnly=true \
         --volume output,kind=host,source=/etc,readOnly=false \
         --mount volume=input,target=/input \
         --mount volume=output,target=/output \
         --set-env=HOST_IP=${DEFAULT_IPV4} \
         --set-env=SERVICE_DNS_NAME=apiserver.testcluster.io \
         quay.io/samsung_cnct/drunkensmee:v0.2 \
         --exec /assets/generate_apiserver.sh
        ExecStopPost=/usr/bin/rkt gc --mark-only
    - name: format-docker.service
      command: start
      content: |
        [Unit]
        Description=Formats the ephemeral drive
        After=dev-xvdf.device
        Requires=dev-xvdf.device
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=/usr/sbin/wipefs -fa /dev/xvdf
        ExecStart=/usr/sbin/mkfs.ext4 /dev/xvdf
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount docker to /var/lib/docker
        Requires=format-docker.service
        After=format-docker.service
        Before=early-docker.service
        Before=docker.service
        [Mount]
        What=/dev/xvdf
        Where=/var/lib/docker
        Type=ext4
    - name: docker.service
      drop-ins:
        - name: 10-wait-docker.conf
          content: |
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount
    - name: early-docker.service
      drop-ins:
        - name: 10-wait-early-docker.conf
          content: |
            [Unit]
            After=var-lib-docker.mount
            Requires=var-lib-docker.mount
    - name: kubelet.service
      command: start
      content: |
        [Unit]
        After=docker.service
        After=kraken-ssl.service
        Requires=docker.service
        Requires=kraken-ssl.service
        [Service]
        EnvironmentFile=/etc/network-environment
        ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/kubernetes-release/release/v1.3.5/bin/linux/amd64/kubelet
        ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
        ExecStart=/opt/bin/kubelet \
          --api_servers=http://127.0.0.1:8080 \
          --register-schedulable=false \
          --allow-privileged=true \
          --config=/etc/kubernetes/manifests \
          --kubeconfig=/etc/kubernetes/kubeconfig.yaml \
          --hostname-override=${DEAFULT_IPV4} \
          --cluster-dns=10.1.0.2 \
          --cluster-domain=cluster.local \
          --tls-cert-file=/etc/kubernetes/ssl/apiserver.pem \
          --tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem \
          --cloud-provider=aws \
          --logtostderr=true
        Restart=always
        RestartSec=10
        [Install]
        WantedBy=multi-user.target
  flannel:
    etcd_endpoints: https://etcd2379.etcd.testcluster.io:2379
    etcd_cafile: /etc/etcd/ssl/client-ca.pem
    etcd_certfile: /etc/etcd/ssl/client.pem
    etcd_keyfile: /etc/etcd/ssl/client-key.pem
  locksmith:
    endpoint: https://etcd2379.etcd.testcluster.io:2379
    etcd_cafile: /etc/etcd/ssl/client-ca.pem
    etcd_certfile: /etc/etcd/ssl/client.pem
    etcd_keyfile: /etc/etcd/ssl/client-key.pem
  update:
    group: stable
    reboot-strategy: etcd-lock