---
- name: Remove credentails generated for system users
  become: yes
  file: path={{ kubernetes_cert_dir }}/known_tokens.csv state=absent

- name: Create credentials file for system users
  become: yes
  file: path={{ kubernetes_cert_dir }}/known_tokens.csv state=touch

- name: Fill out credentails file for system users
  become: yes
  lineinfile: dest={{ kubernetes_cert_dir }}/known_tokens.csv
                regexp=''
                insertafter=EOF
                line="{{ item.value.token }},{{ item.value.name }},{{ item.value.name }}"
  with_dict: "{{ system_users }}"

- name: Remove credentails csv generated for basic auth user
  become: yes
  file: path={{ kubernetes_cert_dir }}/basic_auth.csv state=absent

- name: Remove credentails htpasswd generated for basic auth user
  become: yes
  file: path={{ kubernetes_cert_dir }}/.htpasswd state=absent

- name: Create credentails file for basic auth user
  become: yes
  file: path={{ kubernetes_cert_dir }}/basic_auth.csv state=touch

- name: Fill out credentials file for basic auth user
  become: yes
  lineinfile: dest={{ kubernetes_cert_dir }}/basic_auth.csv
                regexp=''
                insertafter=EOF
                line="{{ kubernetes_basic_auth_user.password }},{{ kubernetes_basic_auth_user.name }},{{ kubernetes_basic_auth_user.name }}"

- name: Set ETCD keys for system users
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" set {{ etcd_key }}/{{ item.value.name }}/token {{ item.value.token }}
  with_dict: "{{ system_users }}"

- name: Create htpasswd file for basic auth user
  htpasswd: >
    path={{ kubernetes_cert_dir }}/.htpasswd
    name={{ kubernetes_basic_auth_user.name }}
    password={{ kubernetes_basic_auth_user.password }}
    owner=core
    group=core
    mode=0640

- name: Set ETCD key for basic auth user
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" set {{ etcd_key }}/{{ kubernetes_basic_auth_user.name }}/basic-auth {{ kubernetes_basic_auth_user.password }}

- name: create marker file
  become: yes
  file: path={{ kubernetes_cert_dir }}/secured_auth state=touch