---
- name: Ensure CA configuration file is created
  become: yes
  template: >
    src=server-ca-config.json.jinja2
    dest={{ kubernetes_cert_dir }}/server-ca-config.json

- name: Ensure CA CSR file is created
  become: yes
  template: >
    src=server-ca-csr.json.jinja2
    dest={{ kubernetes_cert_dir }}/server-ca-csr.json

# docker ansible module doesn't seem to support -w (working folder) switch, so we'll just use shell
- name: Use CloudFlares ssl and PKI management tool to create the certs - gencert
  become: yes
  shell: >
    docker run -i -v {{ kubernetes_cert_dir }}:/opt/kube-ca -w /opt/kube-ca cfssl/cfssl gencert -initca server-ca-csr.json | docker run -i -v {{ kubernetes_cert_dir }}:/opt/kube-ca -w /opt/kube-ca --entrypoint cfssljson cfssl/cfssl -bare kube-ca

- name: Store server ca into etcd
  become: yes
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" set /{{ etcd_key }}/kube-ca-pem < {{ kubernetes_cert_dir }}/kube-ca.pem

- name: Store server ca key into etcd
  become: yes
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" set /{{ etcd_key }}/kube-ca-key-pem < {{ kubernetes_cert_dir }}/kube-ca-key.pem

- name: create marker file
  become: yes
  file: path={{ kubernetes_cert_dir }}/secured_cert state=touch