---
- name: Fill out credentails file for system users
  become: yes
  template: src=known_tokens.csv.jinja2
            dest={{ kubernetes_cert_dir }}/known_tokens.csv

- name: Fill out credentials file for basic auth user
  become: yes
  template: src=basic_auth.csv.jinja2
            dest={{ kubernetes_cert_dir }}/basic_auth.csv

- name: Set ETCD keys for system users
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" set {{ etcd_key }}/{{ item.value.name }}/token {{ item.value.token }}
  with_dict: "{{ system_users }}"

- name: Remove credentails htpasswd generated for basic auth user
  become: yes
  file: path={{ kubernetes_cert_dir }}/.htpasswd state=absent

- name: Create htpasswd file for basic auth user
  htpasswd: >
    path={{ kubernetes_cert_dir }}/.htpasswd
    name={{ kubernetes_basic_auth_user.name }}
    password={{ kubernetes_basic_auth_user.password }}
    owner=core
    group=core
    mode=0640

- name: Set ETCD key for basic auth user
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" set {{ etcd_key }}/{{ kubernetes_basic_auth_user.name }}/basic-auth {{ kubernetes_basic_auth_user.password }}

- name: create marker file
  become: yes
  file: path={{ kubernetes_cert_dir }}/secured_auth state=touch