---
- name: Remove existing server ca
  become: yes
  file: path={{ kubernetes_cert_dir }}/kube-ca.pem state=absent
- name: Remove existing ca key
  become: yes
  file: path={{ kubernetes_cert_dir }}/kube-ca-key.pem state=absent

- name: Wait for ETCD key to be available for server ca
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" get /{{ etcd_key }}/kube-ca-pem
  register: etcd_ca_result
  until: etcd_ca_result.rc == 0
  retries: 120
  delay: 10

- name: Wait for ETCD key to be available for server ca key
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" get /{{ etcd_key }}/kube-ca-key-pem
  register: etcd_ca_key_result
  until: etcd_ca_key_result.rc == 0
  retries: 120
  delay: 10

- name: Load server ca from etcd
  become: yes
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" get /{{ etcd_key }}/kube-ca-pem > {{ kubernetes_cert_dir }}/kube-ca.pem

- name: Load server ca key from etcd
  become: yes
  shell: >
    etcdctl --endpoint "http://{{ etcd_private_ip }}:{{ etcd_port }}" get /{{ etcd_key }}/kube-ca-key-pem > {{ kubernetes_cert_dir }}/kube-ca-key.pem