galaxy_info:
  author: Samsung CNCT
  description:
  company: Samsung CNCT
  license: Apache
  min_ansible_version: 1.2

dependencies:
  - {
      role: '{{ playbook_dir }}/roles/kraken.etcd/kraken.etcd.docker',
      when: "{{ kraken_config.etcd | selectattr('containerConfig.runtime', 'equalto', 'docker') | map(attribute='name') | list | length }} > 0"
    }