---
plugins:
  - name: vagrant-aws
    version: 0.6.0
  - name: vagrant-aws-route53
    version: 0.3.2
  - name: vagrant-triggers
    version: 0.5.0
  - name: excon-middleware-aws-exponential_backoff
    version: 0.0.2
