---
- name: Generate master .units.flanneld.part files
  template: src=units.flanneld.part.jinja2
            dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/master.units.flanneld.part"
  with_items:
    - "{{kraken_config.master}}"

- name: Generate nodes .units.flanneld.part files
  template: src=units.flanneld.part.jinja2
            dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/node.{{item.name}}.units.flanneld.part"
  with_items: "{{kraken_config.node}}"

- name: Generate master .cores.flanneld.part files
  template: src=coreos.flanneld.part.jinja2
            dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/master.coreos.flanneld.part"

- name: Generate nodes .coreos.flanneld.part files
  template: src=coreos.flanneld.part.jinja2
            dest="{{playbook_dir}}/../generated/{{kraken_config.cluster}}/node.{{item.name}}.coreos.flanneld.part"
  with_items: "{{kraken_config.node}}"
