---
- name: Generate master writefiles flannel cni
  template: src=write_files.flannelcni.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/master.write_files.flannelcni.part"

- name: Generate master .units.flanneld.part files
  template: src=units.flanneld.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/master.units.flanneld.part"
  with_items:
    - "{{kraken_config.master}}"

- name: Generate nodes writefiles flannel cni
  template: src=write_files.flannelcni.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/node.{{item.name}}.write_files.flannelcni.part"
  with_items: "{{kraken_config.node}}"

- name: Generate nodes .units.flanneld.part files
  template: src=units.flanneld.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/node.{{item.name}}.units.flanneld.part"
  with_items: "{{kraken_config.node}}"

- name: Generate master .cores.flanneld.part files
  template: src=coreos.flanneld.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/master.coreos.flanneld.part"

- name: Generate nodes .coreos.flanneld.part files
  template: src=coreos.flanneld.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/node.{{item.name}}.coreos.flanneld.part"
  with_items: "{{kraken_config.node}}"
